### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by oliphanj-bsd** [DavidXanatos/wumgr#1]
When I try to build your project I get this message.  
wumgr-master\wumgr\wumgr.csproj" (Build target) (1) ->
(CoreCompile target) ->
  WuMgr.cs(11,7): error CS0246: The type or namespace name 'BrightIdeasSoftware' could not be found (are you missing a
using directive or an assembly reference?) 
 WuMgr.Designer.cs(869,17): error CS0246: The type or namespace name 'BrightIdeasSoftware' could not be found (are you
 missing a using directive or an assembly reference?) [C:\Users\oliphanj\Downloads\wumgr-master\wumgr\wumgr.csproj]
  WuMgr.Designer.cs(870,17):

**Comment by DavidXanatos** [comment]
Try to select the ObjectListView2012 project and build it first, of this does not resolve the issue,
go to the wumgr project->References remove the reference to ObjectListView2012 and than re add it.

Cheers
David X.

**Comment by DavidXanatos** [comment]
The next release 0.6 will not longer require a 3rd party listView library.
