### ISSUE TITLE
View KB article webpage ability

### ISSUE THREAD

**Issue by hl2guide** [DavidXanatos/wumgr#11]
It'd be nice to have an update in the update list have the option to view the associated KB article if one exists.

e.g. https://support.microsoft.com/en-us/help/4467702

_Maybe through a context menu or sidebar button?_
It would be cool if it simply used a web-browser viewport.

**Comment by Yaro7619** [comment]
I join the request

**Comment by Gurthurb** [comment]
Not sure when it was added, perhaps it was after this issue was reported, but there's a **Support Url** link in the top right corner of the wumgr window which does exactly this.
