### ISSUE TITLE
Option "Block Access to WU Servers" is greyed out

### ISSUE THREAD

**Issue by TR66** [DavidXanatos/wumgr#128]
There are reports from at least two different users that the option to "**Block Access to WU Servers**" is greyed out, and can't be selected.  I don't have direct access to these users' systems.  And I haven't been able to reproduce the problem on two different systems where I've tried to duplicate the users' settings.  So at this point I'm really just asking a question here.  What settings or conditions on a Windows 10 system might cause the "Block Access..." option to be greyed out in WUMgr?

**Comment by DavidXanatos** [comment]
iirc its trayed out when the tool is not run as admin

**Comment by TR66** [comment]
In the case of these two users, they have both said that they have the option "**Always run as Administrator**" checked.  Plus, they are logged into their systems as Admin users.  So I don't think that's the reason.  Is there any other condition or setting in Windows that could cause the "**Block Access...**" option to be greyed out?  Is there some Registry entry or Group Policy setting that could cause WUMgr to make that option unavailable?

**Comment by DavidXanatos** [comment]
yes there is when its windows 10 home as this does not respect the GPO used to block said access.

**Comment by TR66** [comment]
Looks like this issue is answered and can be closed.  If there is any documentation though, it should probably include an explanation for users that the "**Block Access...**" option is not supported on Win10 Home Edition.  Just a suggestion.
