### ISSUE TITLE
[1809] Systemsettings.exe crash when automatic updates are disabled

### ISSUE THREAD

**Issue by Lioon2** [DavidXanatos/wumgr#13]
Hello,

Here is a report that we can find on 2 computers on 1809. No issues on 1803.
the error come when i click on update and security panel only

Nom de l’application défaillante SystemSettings.exe, version : 10.0.17763.1, horodatage : 0x9d9d9332
Nom du module défaillant : Windows.UI.Xaml.dll, version : 10.0.17763.1, horodatage : 0xa69151fc
Code d’exception : 0xc000027b
Décalage d’erreur : 0x0000000000707c32
ID du processus défaillant : 0x217c
Heure de début de l’application défaillante : 0x01d47f6a19f9f640
Chemin d’accès de l’application défaillante : C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Chemin d’accès du module défaillant: C:\Windows\System32\Windows.UI.Xaml.dll
ID de rapport : 9b685173-4eae-4de1-a679-4690b40b3d97
Nom complet du package défaillant : windows.immersivecontrolpanel_10.0.2.1000_neutral_neutral_cw5n1h2txyewy
ID de l’application relative au package défaillant : microsoft.windows.immersivecontrolpanel

**Comment by DavidXanatos** [comment]
try ticking the checkbox hide "WU Settings"
