### ISSUE TITLE
What do some of the options do?

### ISSUE THREAD

**Issue by AhoyThere** [DavidXanatos/wumgr#130]
Hello,

first of all let me say thank you for this fantastic tool. However, I'd love some documentation or info about some of the options

What does 'Options -> "Manual" Download/Install' do? Isn't everything there already done manually (which is why we use/love the tool)?

Thanks in advance

**Comment by DavidXanatos** [comment]
Normally we control the steps but let the windows update do the work.
With the manual mode we do dhte downloading and instalation ourselvs.

**Comment by AhoyThere** [comment]
Thank you.
