### ISSUE TITLE
Windows-Function "Search for updates" crashes

### ISSUE THREAD

**Issue by MeboGit** [DavidXanatos/wumgr#16]
Hi,

nice Tool and very helpful when programming (no more restarts).

Anyhow I have following question: After setting to "no automatic updates" and rebooting Win10 the Windows-Function "Search for updates" crashes (will not show up)?!

Thanks and regards

Mebo

**Comment by DavidXanatos** [comment]
yes, that is normal if the update facilitators are disabled,
for that I recomend to just also check the "Hide WU Settings Page" option.
