### ISSUE TITLE
Can you include language files with Japanese added?

### ISSUE THREAD

**Issue by Rukoto** [DavidXanatos/wumgr#17]
Hello,

Can you include language files with Japanese added?
The format has been changed to UTF-16.

[Translation.ini.txt](https://github.com/DavidXanatos/wumgr/files/2613955/Translation.ini.txt)

Kind Regards,
Rukoto

![wumgr_ja-jp](https://user-images.githubusercontent.com/31055417/48991522-8be0ca80-f176-11e8-8737-f6dffdcd0fe6.png)

**Comment by DavidXanatos** [comment]
will do in the next release this week grate thanks
