### ISSUE TITLE
Software Crash When I select Automatic Update

### ISSUE THREAD

**Issue by msebastian100** [DavidXanatos/wumgr#18]
@DavidXanatos @jantari  I choose Automatic update Crashes the program Error: Unhandled exception in the application. 
![2018-12-04_09h24_12](https://user-images.githubusercontent.com/4114151/49428874-6c195a00-f7a7-11e8-8509-68e1d2f776e0.png)

**Comment by DavidXanatos** [comment]
will be fixed in the 0.9a release this week
