### ISSUE TITLE
BallonTip shows incorrect string

### ISSUE THREAD

**Issue by Janek91** [DavidXanatos/wumgr#19]
As on the screenshot below- instead of list of updates, List<MsUpdate> object is casted to string.

![2018-12-05 21_10_53-window](https://user-images.githubusercontent.com/7473827/49541975-8d2b9900-f8d4-11e8-80c7-8f32f12c4b5d.png)

**Comment by DavidXanatos** [comment]
thx fill befixed with 0.9a release
