### ISSUE TITLE
403 Forbidden when trying to download update manually

### ISSUE THREAD

**Issue by akeilox** [DavidXanatos/wumgr#39]
Im on .9a, and started with .8b prior, i cant seem to download the updates manually in either version.

I get the following error for any of the updates, any idea why this is the case?

![image](https://user-images.githubusercontent.com/4035501/50544486-b8827900-0c31-11e9-970f-6f2e5d4e7a08.png)

**Comment by areacode270** [comment]
Same thing has happened to me right out of the gate.  Same message and all.  today is 1/13/2019.  I will have to uninstall it if we don't get this fixed.  I cannot update at all now, as this program bypasses Windows 10 updater.

**Comment by areacode270** [comment]
Am uninstalling.  Cannot update Windows 10 with this program.  Going back to Windows Update

**Comment by jonas-klein** [comment]
On my Windows 10 installation occurs the same issue. It finds updates, but it is not able to download these.
My OS: Windows 10 Pro for Workstations, 10.0.18363

edit: Hm, after repeated reboots and checked and unchecked options, suddenlike it works.

**Comment by DavidXanatos** [comment]
we can only work with what data we get from windows update, if they provide links that cant be downloaded there isn't much that can be done
