### ISSUE TITLE
BUG (0.9a): When run from command line, doesn't return to command prompt without hitting enter

### ISSUE THREAD

**Issue by bcurran3** [DavidXanatos/wumgr#43]
BUG: When run from command line, doesn't return to command prompt without hitting enter.

after hitting ener
![image](https://user-images.githubusercontent.com/14026600/51053746-64f81f80-158f-11e9-94e3-1d4aef9497ce.png)

**Comment by DavidXanatos** [comment]
I know, but I don't know how to fix this.
The tool is not really running as a command line application but as a GUI application it just attaches to the console it was started from in order to print debug messages.
I'm not sure if this even can be fixed and is not an inherent limitation of windows.
