### ISSUE TITLE
Windows Store version is critically out-of-date

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [DavidXanatos/wumgr#52]
I first learned of the existence of WuMgr by finding it on the Windows Store, but whether this version is official or not, it has a number of issues.

The first issue is that it cannot be installed on non-64-bit systems through the Windows store. The second issue with the Windows Store version is that it is an extremely old build (with no way to update it manually because of the nature of Windows Store apps), and the third (and perhaps most critical) issue is that telling that particular build of the program to run in the background causes it to repeatedly crash, and I cannot for the life of me seem to find any way to fix it.

**Comment by DavidXanatos** [comment]
The problem with the Microsoft store is that after this build they did not accept any follow up build, citing reasons like "the tool when run as administrator may not have more functionality than when run regularly".
So I put that on the side so to say, when I will have some spare time I will try to get a up to date build in, but not any time soon.

**Comment by Amaroq-Clearwater** [comment]
Is there any way to make the software more UAC-compliant?
