### ISSUE TITLE
Cannot remove wumgr.

### ISSUE THREAD

**Issue by Andy-KU7T** [DavidXanatos/wumgr#66]
HI, 
I am way behind my updates. Wanted to get the latest downloaded. Latest is 1803 right now, new updates are not seen. How can I uninstall wumgr cleanly so Windows goes back to default?

Thansk
Andy

**Comment by DavidXanatos** [comment]
You only have to uncheck the two checkbox es in the GPO groupe box and set the radio button to auto

**Comment by Guiorgy** [comment]
> You only have to uncheck the two checkbox es in the GPO groupe box and set the radio button to auto

Include the instructions in the README please
