### ISSUE TITLE
Translation - Brazilian Portuguese

### ISSUE THREAD

**Issue by Possessed777** [DavidXanatos/wumgr#67]
[pt]
cap_chk_upd=Por favor, procure por atualizações
cap_new_upd=Novas Atualizações encontradas
col_cat=Categoria
col_date=Data
col_kb=Artigo KB
col_site=Tamanho
col_stat=Estado
col_title=Título
err_admin=Privilégios requeridos não estão disponíveis
err_busy=Outra operação já está em progresso
err_dl=Falhou em baixar
err_file=Não foi possível encontrar o (s) arquivo (s) requerido (s)
err_inst=Instalação falhou
err_int=Erro interno
err_no_sel=Não há atualizações selecionadas ou atualizações elegíveis para a operação
lbl_ac_day=Procurar por atualizações todos os dias
lbl_ac_month=Procurar por atualizações todos os meses
lbl_ac_no=Não procurar por atualizações automaticamente
lbl_ac_week=Procurar por atualizações uma vez por semana
lbl_au=Auto Atualizar
lbl_au_def=Atualização automática(padrão)
lbl_au_dissable=Desativar facilitadores
lbl_au_dl=Apenas baixar
lbl_au_notify=Apenas notificar
lbl_au_off=Desligar atualização automática
lbl_au_time=Instalação agendada
lbl_auto=Executar em segundo plano
lbl_block_ms=Bloquear servidores do WU
lbl_block_upd=Atualizações Ocultadas ({0})
lbl_dl=Baixar wsusscn2.cab
lbl_drv=Incluir Drivers
lbl_fnd_upd=Atualizações do Windows ({0})
lbl_hide=Ocultar configurações do WU
lbl_inst_upd=Atualizações Instaladas ({0})
lbl_man='Manualmente' Baixar/Instalar
lbl_ms=Registrar Microsoft Update
lbl_off=Modo Offline
lbl_old=Incluir substituídas
lbl_old_upd=Histórico de Atualizações ({0})
lbl_opt=Opções
lbl_start=Inicialização
lbl_store=Des. auto atualização da Loja
lbl_support=Url de Suporte
lbl_search=Filtro de pesquisa:
lbl_uac=Sempre como Administrador
menu_about=&Sobre
menu_exit=S&air
menu_refresh=&Atualizar
menu_tools=&Ferramentas
menu_wuau= Serviço do Windows Update
msg_admin_dl=São necessários privilégios de administrador para baixar atualizações usando os serviços de atualização do Windows. Baixe usando 'Manualmente'.
msg_admin_inst=São necessários privilégios de Administrador para instalar atualizações.
msg_admin_rem=São necessários privilégios de Administrador para remover atualizações.
msg_admin_req=O {0} requer privilégios de Administrador para instalar atualizações
msg_chk_upd={0} não foi possível verificar se há atualizações por {1} dia(s), por favor, verifique as atualizações manualmente e resolva possíveis problemas
msg_dl_done=Atualizações baixadas para {0}, pronto para ser instalado pelo usuário.
msg_dl_err=Atualizações baixadas para {0}, algumas atualizações não foram baixadas.
msg_err={0} falhou: {1}.
msg_gpo=Sua versão do Windows não respeita os padrões de Diretiva de Grupo, para manter as atualizações automáticas do Windows bloqueadas, os serviços de facilitação de atualização devem ser desativados.
msg_inst_done=Atualizações instaladas com sucesso, no entanto, uma reinicialização é necessária.
msg_inst_err=A Instalação de algumas Atualizações falhou, também é necessária uma reinicialização.
msg_new_upd={0} Encontrou {1} novas atualizações, revise as atualizações e instale-as
msg_ro_wrk_dir=Não é possível gravar no diretório de trabalho: {0}
msg_running=Aplicativo já está em execução.
msg_tool_err=Falha ao iniciar a ferramenta
msg_wuau=O Serviço do Windows Update não está disponível, tentar iniciá-lo?
op_cancel=Cancelando Operação
op_check=Procurando por Atualizações
op_dl=Baixando Atualizações
op_inst=Instalando Atualizações
op_prep=Preparing Check
op_rem=Removendo Atualizações
op_unk=Operação Desconhecida
stat_abbort=Abortada
stat_beta=Beta
stat_block=Ocultar
stat_dl=Baixar
stat_excl=Exclusiva
stat_failed=Falhou
stat_in_prog=Em Progresso
stat_install=Instalada
stat_mand=Obrigatória
stat_not_start=Não Iniciada
stat_pending=Pendente
stat_reboot=Precisa de Reinicialização
stat_rem=Removível
stat_sel=(!)
stat_success=Sucedida
stat_success_2=Sucedida com Erros
tip_cancel=Cancelar
tip_dl=Baixar
tip_hide=Ocultar
tip_inst=Instalar
tip_lnk=Obter Links
tip_rem=Desinstalar
tip_search=Procurar
msg_disable_au=Para que a nova configuração entre em vigor, é necessária uma reinicialização.
lbl_group=Agrupar Atualizações
lbl_all=Selecionar Todas
lbl_patreon=Suporte WuMgr no Patreon
lbl_github=Visitar WuMgr no GitHub

**Comment by Possessed777** [comment]
edited. fixed text spacing by replacing or adapting some strings.

**Comment by DavidXanatos** [comment]
thanks will be added to the next release
