### ISSUE TITLE
Translation - Italian

### ISSUE THREAD

**Issue by irondave** [DavidXanatos/wumgr#68]
[it]
cap_chk_upd=Verificare la disponibilità di aggiornamenti
cap_new_upd=Nuovi aggiornamenti trovati
col_cat=Categoria
col_date=Data
col_kb=Articolo KB
col_site=Dimensioni
col_stat=Stato
col_title=Titolo
err_admin=Privilegi richiesti non disponibili
err_busy=Altra operazione già in progresso
err_dl=Scaricamento fallito
err_file=File richiesto non trovato
err_inst=Installazione fallita
err_int=Errore interno
err_no_sel=Nessun aggiornamento selezionato o nessun aggiornamento eleggibile per l'operazione
lbl_ac_day=Cerca aggiornamenti tutti i giorni
lbl_ac_month=Cerca aggiornamenti tutti i mesi
lbl_ac_no=Non cercare aggiornamenti automaticamente
lbl_ac_week=Cerca aggiornamenti una volta alla settimana
lbl_au=Aggiornamento automatico
lbl_au_def=Aggiornamento automatico (default)
lbl_au_dissable=Disattiva Agevolatore Aggiornamenti
lbl_au_dl=Scarica solamente
lbl_au_notify=Notifica solamente
lbl_au_off=Disattiva Aggiornamenti Automatici
lbl_au_time=Installazione programmata
lbl_auto=Avvia in background
lbl_block_ms=Blocca Accesso ai Server WU
lbl_block_upd=Aggiornamenti Nascosti ({0})
lbl_dl=Scarica wsusscn2.cab
lbl_drv=Includi Driver
lbl_fnd_upd=Aggiornamenti di Windows ({0})
lbl_hide=Nascondi Pagina Impostazioni WU
lbl_inst_upd=Aggiornamenti Installati ({0})
lbl_man=Scaricamento/Installazione'Manuale'
lbl_ms=Registra Aggiornamenti Microsoft
lbl_off=Modo Offline
lbl_old=Includi sostituti
lbl_old_upd=Storico Aggiornamenti ({0})
lbl_opt=Opzioni
lbl_start=Avvio
lbl_store=Disattiva Aggiornamenti Automatici Store
lbl_support=Url Supporto
lbl_search=Filtro Ricerca:
lbl_uac=Avvia sempre come Amministratore
menu_about=&Circa
menu_exit=E&sci
menu_refresh=&Aggiorna
menu_tools=&Strumenti
menu_wuau=Servizio Aggiornamenti Windows
msg_admin_dl=Privilegi di Amministratore richiesti per scaricare aggiornamenti utilizzando i sevizi aggiornamenti windows. Utilizza scaricamento 'Manuale' in alternativa.
msg_admin_inst=Richiesti privilegi di Amministratore per installare gli aggiornamenti.
msg_admin_rem=Richiesti privilegi di Amministratore per rimuovere gli aggiornamenti.
msg_admin_req={0} richiede privilegi di Amministratore per installare gli aggiornamenti.
msg_chk_upd={0} non è stato possibile verificare la disponibilità di aggiornamenti per {1} giorni, cerca aggiornamenti manualmente e risolvere possibili problemi
msg_dl_done=Aggiornamento scaricato in {0}, pronto per essere installato dall'utente.
msg_dl_err=Aggiornamento scaricato in {0}, alcuni aggiornamenti non sono stati scaricati.
msg_err={0} fallito: {1}.
msg_gpo=La tua versione di Windows non rispetta gli standard GPO, per mantenere gli aggiornamenti di Windows bloccati, i servizi di agevolazione degli aggiornamenti devono essere disabilitati.
msg_inst_done=Agiornamento installato con successo, tuttavia, è richiesto il riavvio del sistema.
msg_inst_err=L'installazione di alcuni Aggiornamenti è fallita, inoltre è richiesto il riavvio del sistema.
msg_new_upd={0} ha trovato {1} nuovi aggiornamenti, controlla gli aggiornamenti ed installali
msg_ro_wrk_dir=Impossibile scrivere nella directory di lavoro: {0}
msg_running=L'applicazione è già in esecuzione.
msg_tool_err=Avvio dello strumento fallito
msg_wuau=Servizio Aggiornamenti di Windows non è disponibile, provare ad avviarlo?
op_cancel=Annullamento Operazione
op_check=Verifica aggiornamenti
op_dl=Scaricando Aggiornamenti
op_inst=Installando Aggiornamenti
op_prep=Preparazione Controllo
op_rem=Rimuovendo Aggiornamenti
op_unk=Operazione Sconosciuta
stat_abbort=Abortito
stat_beta=Beta
stat_block=Nascosto
stat_dl=Scaricato
stat_excl=Esclusivo
stat_failed=Fallito
stat_in_prog=In Progresso
stat_install=Installato
stat_mand=Obbligatorio
stat_not_start=Non Avviato
stat_pending=In attesa
stat_reboot=Riavvio Necessario
stat_rem=Removibile
stat_sel=(!)
stat_success=Riuscito
stat_success_2=Riuscito con Errori
tip_cancel=Annulla
tip_dl=Scarica
tip_hide=Nascondi
tip_inst=Installa
tip_lnk=Ottieni collegamenti
tip_rem=Disinstalla
tip_search=Cerca
msg_disable_au=Per rendere pienamente operativa la nuova configurazione è necessario un riavvio.
lbl_group=Gruppi di Aggiornamenti
lbl_all=Seleziona Tutti
lbl_patreon=Supporta WuMgr su Patreon
lbl_github=Visita WuMgr su GitHub

**Comment by DavidXanatos** [comment]
thanks will be added to next build
