### ISSUE TITLE
Update Japanese translation

### ISSUE THREAD

**Issue by Rukoto** [DavidXanatos/wumgr#70]
Hi.
Japanese translation has been improved, so please merge it.
Thanks!

[Translation.ja_only.zip](https://github.com/DavidXanatos/wumgr/files/3746838/Translation.ja_only.zip)

**Comment by DavidXanatos** [comment]
thanks i updated the release zip on github with the new translation
thx
David

**Comment by Rukoto** [comment]
really sorry.
I updated the zip several times because I uploaded the wrong content.
Please re-merge with the latest zip as we will not update any more.

**Comment by DavidXanatos** [comment]
No problem...
done.
