### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by MikeZTM** [DavidXanatos/wumgr#74]
This app does not support HiDPI displays.

Since this is a WinForm App. Just targeting .net framework 4.7 and add 

`  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="PerMonitorV2"/>
  </System.Windows.Forms.ApplicationConfigurationSection>`

in app.config will enable HiDPI support automatically.

I tested it locally and this works out of the box.

**Comment by DavidXanatos** [comment]
Thanks I will add that to the next build

**Comment by DavidXanatos** [comment]
added in 1.1

**Comment by koitsu** [comment]
https://github.com/DavidXanatos/wumgr/issues/119
