### ISSUE TITLE
“Installed Updates” vs “Update History”.

### ISSUE THREAD

**Issue by asjones987** [DavidXanatos/wumgr#81]
I have not figured out what “Installed Updates” means vs “Update History”. I installed some updates and they are now listed in the “Installed Updates” section and not History. When I get out of WuMgr and back in the Installed Updates do not show up until i do a check for updates. I ran the the Nirsoft Windows Update History https://www.nirsoft.net/utils/windows_updates_history_viewer.html I does not show any of the items in the “Installed Updates” section (that only show on check for update).

What am I missing?

**Comment by DavidXanatos** [comment]
Installed updates are updates that are currently installed in the system, you may uninstall them.
Update History should show the history i.e. when upates were installed, mo mater if they were uninstalled later. You can also clear the update history.

**Comment by asjones987** [comment]
thanks for the response and thanks for the great tool.
A few things confused me and another person I was working with
1. Installed Updates list only populated when we did a "Search" for new updates. If the updates are "installed' why did they not populate the "Installed Updates" it not populate like the "Update History" section?
2. Items in the Installed Updates are not listed in the Update History and vice versa. We thought if it was installed then it should be listed in history.
3. We know it is another tool but the Nirsoft Windows Update History Viewer was also not showing any items that were just listed in the Installed Update list.
Those 3 items made us wonder if the updates were actually installed. The Nirsoft tool may not be perfect but we thought it was a good start. 

You also mentioned that you can clear the update history. I did not see a way in WuMgr to do that. All the key buttons looked to be grayed out.

thanks

Alan
