### ISSUE TITLE
Incorrect update sizes

### ISSUE THREAD

**Issue by johanbar** [DavidXanatos/wumgr#84]
Hi David,

Thanks for a wonderful program.

It reports some update sizes incorrectly on server 2019, and fails.

![image](https://user-images.githubusercontent.com/22575502/73121750-2492f600-3f86-11ea-9387-499f2e318151.png)

I suspect it is summing patches not relevant (and their sizes also).

**Comment by johanbar** [comment]
See my answer in #59
Its an issue with the Microsoft API and what it reports, not something thjs tool has control over

oh well.

Have you thought about scraping the correct sizes off https://www.catalog.update.microsoft.com/Home.aspx and pulling from there?

**Comment by DavidXanatos** [comment]
mmh... I don't think crawling the update catalog for size only is worth while.
If we would need that for something functionally relevant that would be a different story.
