### ISSUE TITLE
Source as is does not build

### ISSUE THREAD

**Issue by alexfotios** [DavidXanatos/wumgr#86]
KnownFolders.cs(54,148,54,155): error CS1003: Syntax error, ',' expected
----
 int result = SHGetKnownFolderPath(new Guid(_knownFolderGuids[(int)knownFolder]), (uint)flags, new IntPtr(defaultUser ? -1 : 0), out IntPtr outPath);

but "outPath" is defined nowhere in the project

**Comment by DavidXanatos** [comment]
indeed it is not, for some reason on my system it builds, i guess its related to the VS version.
i have added a definition for the next built.

**Comment by alexfotios** [comment]
Thank you - will check it!
