### ISSUE TITLE
Delete downloaded updates

### ISSUE THREAD

**Issue by Guiorgy** [DavidXanatos/wumgr#88]
Is it possible to delete downloaded (not yet installed) update files? I have no plans of ever installing those.

**Comment by DavidXanatos** [comment]
not from the UI you would need to go tothe download directory and delete the appropriate sub dir manually

**Comment by Guiorgy** [comment]
The app is given admin rights right? can it not be implemented?

PS. I deleted the content of C:\Windows\SoftwareDistribution\Download, and it still says downloaded

**Comment by DavidXanatos** [comment]
emm...delting in maual download mode is simple, deleting from the windows update dir is difficult as the paths are not known, i will check though if i can find them out somehow
